// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go

// Package account is a generated GoMock package.
package account

import (
	context "context"
	io "io"
	reflect "reflect"

	account "github.com/arifinhermawan/bubi/internal/usecase/account"
	gomock "github.com/golang/mock/gomock"
)

// MockaccountUCManager is a mock of accountUCManager interface.
type MockaccountUCManager struct {
	ctrl     *gomock.Controller
	recorder *MockaccountUCManagerMockRecorder
}

// MockaccountUCManagerMockRecorder is the mock recorder for MockaccountUCManager.
type MockaccountUCManagerMockRecorder struct {
	mock *MockaccountUCManager
}

// NewMockaccountUCManager creates a new mock instance.
func NewMockaccountUCManager(ctrl *gomock.Controller) *MockaccountUCManager {
	mock := &MockaccountUCManager{ctrl: ctrl}
	mock.recorder = &MockaccountUCManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockaccountUCManager) EXPECT() *MockaccountUCManagerMockRecorder {
	return m.recorder
}

// LogIn mocks base method.
func (m *MockaccountUCManager) LogIn(ctx context.Context, email, password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogIn", ctx, email, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LogIn indicates an expected call of LogIn.
func (mr *MockaccountUCManagerMockRecorder) LogIn(ctx, email, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogIn", reflect.TypeOf((*MockaccountUCManager)(nil).LogIn), ctx, email, password)
}

// LogOut mocks base method.
func (m *MockaccountUCManager) LogOut(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogOut", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogOut indicates an expected call of LogOut.
func (mr *MockaccountUCManagerMockRecorder) LogOut(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogOut", reflect.TypeOf((*MockaccountUCManager)(nil).LogOut), ctx, userID)
}

// UpdatePassword mocks base method.
func (m *MockaccountUCManager) UpdatePassword(ctx context.Context, param account.UpdatePasswordParam) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", ctx, param)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockaccountUCManagerMockRecorder) UpdatePassword(ctx, param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockaccountUCManager)(nil).UpdatePassword), ctx, param)
}

// UpdateUserAccount mocks base method.
func (m *MockaccountUCManager) UpdateUserAccount(ctx context.Context, param account.UpdateUserAccountParam) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserAccount", ctx, param)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserAccount indicates an expected call of UpdateUserAccount.
func (mr *MockaccountUCManagerMockRecorder) UpdateUserAccount(ctx, param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserAccount", reflect.TypeOf((*MockaccountUCManager)(nil).UpdateUserAccount), ctx, param)
}

// UserSignUp mocks base method.
func (m *MockaccountUCManager) UserSignUp(ctx context.Context, email, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserSignUp", ctx, email, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// UserSignUp indicates an expected call of UserSignUp.
func (mr *MockaccountUCManagerMockRecorder) UserSignUp(ctx, email, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserSignUp", reflect.TypeOf((*MockaccountUCManager)(nil).UserSignUp), ctx, email, password)
}

// MockinfraProvider is a mock of infraProvider interface.
type MockinfraProvider struct {
	ctrl     *gomock.Controller
	recorder *MockinfraProviderMockRecorder
}

// MockinfraProviderMockRecorder is the mock recorder for MockinfraProvider.
type MockinfraProviderMockRecorder struct {
	mock *MockinfraProvider
}

// NewMockinfraProvider creates a new mock instance.
func NewMockinfraProvider(ctrl *gomock.Controller) *MockinfraProvider {
	mock := &MockinfraProvider{ctrl: ctrl}
	mock.recorder = &MockinfraProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockinfraProvider) EXPECT() *MockinfraProviderMockRecorder {
	return m.recorder
}

// JsonUnmarshal mocks base method.
func (m *MockinfraProvider) JsonUnmarshal(input []byte, dest interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JsonUnmarshal", input, dest)
	ret0, _ := ret[0].(error)
	return ret0
}

// JsonUnmarshal indicates an expected call of JsonUnmarshal.
func (mr *MockinfraProviderMockRecorder) JsonUnmarshal(input, dest interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JsonUnmarshal", reflect.TypeOf((*MockinfraProvider)(nil).JsonUnmarshal), input, dest)
}

// ReadAll mocks base method.
func (m *MockinfraProvider) ReadAll(input io.Reader) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAll", input)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAll indicates an expected call of ReadAll.
func (mr *MockinfraProviderMockRecorder) ReadAll(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAll", reflect.TypeOf((*MockinfraProvider)(nil).ReadAll), input)
}
